Repository pivotal-cf/docs-rabbitmq-pcf, pull requests merged in 2019-04, with the labels that each got.

#409 Rename errand to match name in tile UI
  install-config-pp.html.md.erb
  install-config.html.md.erb
Labels: unscheduled

#406 Rename errand to match name in tile UI
  install-config-pp.html.md.erb
  install-config.html.md.erb
Labels: unscheduled

#407 Rename errand to match name in tile UI
  install-config-pp.html.md.erb
  install-config.html.md.erb
Labels: unscheduled

#408 Rename errand to match name in tile UI
  install-config-pp.html.md.erb
  install-config.html.md.erb
Labels: unscheduled

#410 Add note on known issue during upgrade
  releases.html.md.erb
  upgrade.html.md.erb
Labels: unscheduled

#411 Replaced example binding RMQ IPs with BOSH DNS names
  use.html.md.erb
Labels: unscheduled

#412 Update TLS Docs to represent new TLS enable command
  use.html.md.erb
Labels: in progress

#413 Remove 3.6 references
  ondemand.html.md.erb
Labels: unscheduled

#414 [on-demand] Replaced instances of IPs with DNS names
  use.html.md.erb
  vcap-services.html.md.erb
Labels: unscheduled

#416 Updates TLS config to include 'enforced' option
  images/security.png
  install-config.html.md.erb
Labels: unscheduled

#417 Add findings from BOSH DNS to docs
  install-config.html.md.erb
  troubleshoot-instances.html.md.erb
  use.html.md.erb
Labels: unscheduled

#418 Update on-demand, pre-provisioned table
  ondemand.html.md.erb
Labels: unscheduled

#419 Update on-demand/pre-provisioned comparison table
  ondemand.html.md.erb
Labels: unscheduled

#420 Update on-demand/pre-provisioned comparison table
  ondemand.html.md.erb
Labels: unscheduled

#421 Clarify BOSH DNS resolution section
  use.html.md.erb
Labels: unscheduled

#422 Add docs about turning off TLS
  images/security.png
  install-config.html.md.erb
  use.html.md.erb
Labels: in progress

#423 [pre-provisioned] Update HAProxy ports description
  install-config-pp.html.md.erb
Labels: unscheduled

#424 [pre-provisioned] Update HAProxy ports description
  install-config-pp.html.md.erb
Labels: unscheduled

#425 [pre-provisioned] Update HAProxy ports description
  install-config-pp.html.md.erb
Labels: unscheduled

#426 [pre-provisioned] Update HAProxy ports description
  install-config-pp.html.md.erb
Labels: unscheduled

#427 Correct VCAP_SERVICES entry
  reference.html.md.erb
Labels: unscheduled

#428 Specify port needed on Bosh Director for Credhub
  about.html.md.erb
Labels: unscheduled

#429 Add notes about required port on Bosh Director
  about.html.md.erb
  releases.html.md.erb
Labels: unscheduled

#430 Add 1.16 first minor (1.16.1) release notes
  index.html.md.erb
  releases.html.md.erb
Labels: unscheduled

#431 Clarify docs about RMQ Management UI
  images/cli_manage.jpeg
  managing.html.md.erb
Labels: unscheduled

#432 Document ability to enable plugins on a platform scope
  images/on-demand-plugins-operator.png
  install-config.html.md.erb
  use.html.md.erb
Labels: scheduled
