Repository pivotal-cf/docs-rabbitmq-pcf, pull requests merged in 2019-03, with the labels that each got.

#388 Add mqtt to list of plugins that can be enabled
  install-config.html.md.erb
  releases.html.md.erb
Labels: unscheduled

#393 Add 1.15.5 release notes
  index.html.md.erb
  releases.html.md.erb
Labels: scheduled

#392 Add 1.14.8 release notes
  index.html.md.erb
  releases.html.md.erb
Labels: scheduled

#391 Add 1.13.16 release notes
  index.html.md.erb
  releases.html.md.erb
Labels: scheduled

#394 Removing all releases with RMQ 3.7.7
  releases.html.md.erb
Labels: unscheduled

#397 Release notes for 1.13.17
  index.html.md.erb
  releases.html.md.erb
Labels: unscheduled

#396 Release notes for 1.14.9
  index.html.md.erb
  releases.html.md.erb
Labels: unscheduled

#395 Release notes for 1.15.6
  index.html.md.erb
  releases.html.md.erb
Labels: in progress

#402 Uploads new images for errands
  images/errands-installation-pending-changes.png
  images/errands-installation.png
Labels: unscheduled

#401 Uploads new image and removes reference to old ops man screen
  images/errands-installation-pending-changes.png
  images/errands-installation.png
  install-config-pp.html.md.erb
Labels: unscheduled

#400 Uploads new image and removes reference to old ops man screen
  images/errands-installation-pending-changes.png
  images/errands-installation.png
  install-config-pp.html.md.erb
Labels: unscheduled

#405 Release notes for 1.15.7
  index.html.md.erb
  releases.html.md.erb
Labels: unscheduled

#404 Release notes for 1.14.10
  index.html.md.erb
  releases.html.md.erb
Labels: unscheduled

#403 Release Notes for v1.13.18
  index.html.md.erb
  releases.html.md.erb
Labels: in progress
