Repository pivotal-cf/docs-rabbitmq-pcf, pull requests merged in 2021-03, with the labels that each got.

#581 Allow tier-1 plugins to be enabled in on-demand in v2.x
  install-config.html.md.erb
Labels: unscheduled

#578 Add release notes for 1.21.1
  install-config-pp.html.md.erb
  install-config.html.md.erb
  releases.html.md.erb
Labels: in progress

#579 Add release notes for 1.20.4
  install-config-pp.html.md.erb
  install-config.html.md.erb
  releases.html.md.erb
Labels: in progress

#580 Add release notes for 1.19.6
  install-config-pp.html.md.erb
  install-config.html.md.erb
  releases.html.md.erb
Labels: in progress

#586 Remove support for TLS 1.0 and TLS 1.1 in tile v2.x
  images/config_tls.png
  images/configure-oauth.png
  install-config-pp.html.md.erb
  install-config.html.md.erb
  releases.html.md.erb
Labels: unscheduled

#584 Add 1.20.5 release notes
  index.html.md.erb
  install-config-pp.html.md.erb
  releases.html.md.erb
Labels: scheduled

#585 Add release notes for 1.21.2
  index.html.md.erb
  install-config-pp.html.md.erb
  releases.html.md.erb
Labels: scheduled

#587 Add documentation for override config feature
  expert-override-config.html.md.erb
  images/override-adv-config-od.png
  images/override-adv-config-pp.png
  images/override-config-od.png
  images/plan-1-configuration.png
  install-config-pp.html.md.erb
  install-config.html.md.erb
Labels: unscheduled

#588 Fix Title generation in Expert mode doc
  expert-override-config.html.md.erb
Labels: unscheduled

#591 1.20: Clarification about non-SSL protocols when TLS enabled
  install-config-pp.html.md.erb
Labels: unscheduled

#590 1.21: Clarification about non-SSL protocols when TLS enabled
  install-config-pp.html.md.erb
Labels: unscheduled

#589 2.0: Clarification about non-SSL protocols when TLS enabled
  install-config-pp.html.md.erb
Labels: unscheduled

#594 Metrics breaking changes
  monitor-pp.html.md.erb
  monitor.html.md.erb
  releases.html.md.erb
Labels: unscheduled

#595 Update release notes for 2.0.0
  releases.html.md.erb
Labels: unscheduled
